services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.external-url=https://dojo-task.com/prometheus/'
      - '--web.route-prefix=/'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`dojo-task.com`, `www.dojo-task.com`) && PathPrefix(`/prometheus`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.tls.certresolver=myresolver"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.middlewares.prometheus-stripprefix.stripprefix.prefixes=/prometheus"
      - "traefik.http.routers.prometheus.middlewares=prometheus-stripprefix"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SERVER_DOMAIN=dojo-task.com
      - GF_SERVER_ROOT_URL=https://dojo-task.com/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`dojo-task.com`, `www.dojo-task.com`) && PathPrefix(`/grafana`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./monitoring/loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/tmp/loki
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loki.rule=Host(`dojo-task.com`, `www.dojo-task.com`) && PathPrefix(`/loki`)"
      - "traefik.http.routers.loki.entrypoints=websecure"
      - "traefik.http.routers.loki.tls=true"
      - "traefik.http.routers.loki.tls.certresolver=myresolver"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"
      - "traefik.http.middlewares.loki-stripprefix.stripprefix.prefixes=/loki"
      - "traefik.http.routers.loki.middlewares=loki-stripprefix"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
    networks:
      - app-network
    command:
      - "-config.file=/etc/promtail/config.yml"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg
    networks:
      - app-network
    command:
    - '--housekeeping_interval=10s'
    - '--url_base_prefix=/cadvisor'
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.cadvisor.rule=Host(`dojo-task.com`, `www.dojo-task.com`) && PathPrefix(`/cadvisor`)"
    - "traefik.http.routers.cadvisor.entrypoints=websecure"
    - "traefik.http.routers.cadvisor.tls=true"
    - "traefik.http.routers.cadvisor.tls.certresolver=myresolver"
    - "traefik.http.services.cadvisor.loadbalancer.server.port=8080"
    - "traefik.http.middlewares.cadvisor-stripprefix.stripprefix.prefixes=/cadvisor"
    - "traefik.http.routers.cadvisor.middlewares=cadvisor-stripprefix"
  
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)'
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node-exporter.rule=Host(`dojo-task.com`, `www.dojo-task.com`) && PathPrefix(`/node-exporter`)"
      - "traefik.http.routers.node-exporter.entrypoints=websecure"
      - "traefik.http.routers.node-exporter.tls=true"
      - "traefik.http.routers.node-exporter.tls.certresolver=myresolver"
      - "traefik.http.services.node-exporter.loadbalancer.server.port=9100"
      - "traefik.http.middlewares.node-exporter-stripprefix.stripprefix.prefixes=/node-exporter"
      - "traefik.http.routers.node-exporter.middlewares=node-exporter-stripprefix"


networks:
  app-network:
    external: true

volumes:
  grafana-data:
    driver: local
  loki-data:
    driver: local