name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'

  #     - name: Install dependencies and run frontend lint
  #       working-directory: ./frontend
  #       run: |
  #         npm install
  #         npm run lint

  #     - name: Run backend lint
  #       working-directory: ./backend
  #       run: |
  #         pip install flake8
  #         flake8 .

  deploy:
    # needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Check if Docker is installed and running
            if ! command -v docker &> /dev/null; then
              echo "Docker is not installed"
              exit 1
            fi
            
            # Check if Docker Compose is installed
            if ! command -v docker-compose &> /dev/null; then
              echo "Docker Compose is not installed"
              exit 1
            fi
            
            # Check if Docker daemon is running
            if ! docker info &> /dev/null; then
              echo "Docker daemon is not running"
              exit 1
            fi
            
            cd /path/to/your/project
            
            # Pull latest changes
            git pull origin main
            
            # Stop and remove existing containers
            docker-compose down || true
            
            # Build and start new containers
            docker-compose up -d --build
            
            # Check if containers are running
            if ! docker-compose ps | grep -q "Up"; then
              echo "Failed to start containers"
              docker-compose logs
              exit 1
            fi
